parameters:
- name: variable_group_name
  displayName: Variable Group
  type: string
  default: 'Image Generation Variables'
- name: agent_pool
  displayName: Agent Pool
  type: string
  default: CI Windows2022
- name: repository_base_path
  displayName: Scripts Path
  type: string
  default: .
- name: vmss_names
  displayName: VmssNames
  type: string
- name: build_stage_job_name
  displayName: Name of the stage and job that builds the image
  type: string
  default: buildagent_template_vm
  
jobs:
- job: updatevmss
  displayName: Update Virtual Machine Scale Set
  timeoutInMinutes: 600
  cancelTimeoutInMinutes: 30
  pool: 
    name: ${{ parameters.agent_pool }}

  variables:
  - name: ManagedImageName
    value: $[stageDependencies.${{ parameters.build_stage_job_name }}.generate_image.outputs['setVars.ManagedImageNameOutput'] ]
  - group: ${{ parameters.variable_group_name }}
  - name: VmssNames
    value: ${{ parameters.vmss_names }}
  - group: ${{ parameters.variable_group_name }}

  steps:
  - checkout: self
  - ${{ if ne(parameters.repository_base_path, '.') }}:
    - checkout: ${{ parameters.repository_base_path }}
  - task: PowerShell@2
    displayName: 'Update Virtual Machine Scale Set'
    inputs:
      targetType: filePath
      filePath: ${{ parameters.repository_base_path }}/scripts/update-vmss.ps1
      arguments: -ClientId $(CLIENT_ID) `
                 -ClientSecret $(CLIENT_SECRET) `
                 -ResourceGroup $(AZURE_RESOURCE_GROUP) `
                 -AgentsResourceGroup $(AZURE_AGENTS_RESOURCE_GROUP) `
                 -SubscriptionId $(AZURE_SUBSCRIPTION) `
                 -TenantId $(AZURE_TENANT) `
                 -ManagedImageName $(ManagedImageName) `
                 -VmssNames $(VmssNames)
